"""Wiki update suggestion generator + atomic apply (W3 hook helper)."""
from __future__ import annotations

import json
import os
import re
import tempfile
from datetime import date
from pathlib import Path

from kb.wiki_lint import (
    lint_backlink_validity,
    lint_citation_integrity,
    lint_contradicts_existing,
    lint_staleness,
    log_lint_failure,
)

DEFAULT_BUFFER_DIRS = [Path(".dev-runtime/entity_buffer"), Path("entity_buffer")]
_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slugify(name: str) -> str:
    return _SLUG_RE.sub("-", str(name).lower()).strip("-")


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=str(path.parent), delete=False, suffix=".tmp"
    ) as f:
        f.write(content)
        tmp = Path(f.name)
    os.rename(tmp, path)


def _build_page(slug: str, hashes: list[str], today: str, confidence: str) -> str:
    title = slug.replace("-", " ").title()
    srcs = "\n".join(f"  - article:{h}" for h in hashes)
    cite = " ".join(f"^[article:{h}]" for h in hashes[:2])
    return (
        f"---\ntitle: {title}\ncreated: {today}\nlast_updated: {today}\n"
        f"sources:\n{srcs}\nconfidence_level: {confidence}\n---\n\n"
        f"# {title}\n\nAuto-generated by W3 hook on {today}. {cite}\n"
    )


def generate_wiki_suggestions(
    article_hashes: list[str], wiki_root: Path, db_conn,
    min_frequency: int = 2, entity_buffer_dirs: list[Path] | None = None,
) -> list[dict]:
    buf_dirs = entity_buffer_dirs or DEFAULT_BUFFER_DIRS
    entity_to_hashes: dict[str, set[str]] = {}
    for h in article_hashes:
        if not db_conn.execute("SELECT 1 FROM articles WHERE content_hash=?", (h,)).fetchone():
            continue
        for d in buf_dirs:
            p = Path(d) / f"{h}_entities.json"
            if not p.exists():
                continue
            for e in json.loads(p.read_text(encoding="utf-8")).get("raw_entities", []):
                name = e.get("name", "") if isinstance(e, dict) else str(e)
                if (slug := _slugify(name)):
                    entity_to_hashes.setdefault(slug, set()).add(h)
            break
    today = date.today().isoformat()
    suggestions: list[dict] = []
    for slug, hset in entity_to_hashes.items():
        if len(hset) < min_frequency:
            continue
        page_path = Path(wiki_root) / "entities" / f"{slug}.md"
        hashes_sorted = sorted(hset)
        suggestions.append({
            "type": "update" if page_path.exists() else "new",
            "entity_slug": slug, "page_path": str(page_path),
            "content": _build_page(slug, hashes_sorted, today,
                                   "medium" if page_path.exists() else "low"),
            "source_articles": hashes_sorted,
        })
    return suggestions


def apply_suggestion_atomic(suggestion: dict, db_conn, wiki_root: Path | None = None) -> bool:
    page_path = Path(suggestion["page_path"])
    root = Path(wiki_root) if wiki_root else page_path.parent.parent
    known = {r[0] for r in db_conn.execute("SELECT content_hash FROM articles").fetchall()}
    page_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_check = page_path.parent / f".{page_path.stem}.lint.tmp"
    tmp_check.write_text(suggestion["content"], encoding="utf-8")
    excerpt = suggestion["content"][:120]
    checks = [
        ("lint_citation_integrity", lambda: lint_citation_integrity(tmp_check, known)),
        ("lint_backlink_validity", lambda: lint_backlink_validity(suggestion["content"], root)),
    ]
    if suggestion["type"] == "update" and page_path.exists():
        checks.append(("lint_contradicts_existing", lambda: lint_contradicts_existing(suggestion["content"], page_path)))
        checks.append(("lint_staleness", lambda: lint_staleness(tmp_check, max_days=180)))
    failed = False
    for name, fn in checks:
        if (fails := fn()):
            log_lint_failure({"page_path": str(page_path), "lint_name": name,
                              "failures": fails, "suggestion_excerpt": excerpt})
            failed = True
    tmp_check.unlink(missing_ok=True)
    if failed:
        return False
    _atomic_write(page_path, suggestion["content"])
    return True
