#!/usr/bin/env bash
# ISSUES #47: wire the LightRAG atomic-write monkey-patch into both Aliyun
# venvs via sitecustomize.py, so it survives `pip install --force-reinstall
# lightrag` (which would otherwise revert the in-place vendored edit from
# 260608-e8l and re-open the 6/7 graphml-truncation corruption class).
#
# Idempotent: re-running overwrites the two sitecustomize.py files with the
# same content. Safe to run after every Aliyun `git pull` + deploy.
#
# Usage (on Aliyun):
#   cd /root/OmniGraph-Vault && bash scripts/apply_lightrag_atomic_write_patch.sh
#
# The sitecustomize.py is auto-imported by CPython at interpreter startup if it
# is on sys.path. site-packages/ is always on sys.path, so dropping the file
# there guarantees the patch fires for every process using that venv (ingest
# cron uses venv-aim1, kb-api uses venv).
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# sitecustomize body: prepend the repo root to sys.path so `import lib...`
# resolves regardless of CWD, then apply the patch fail-soft.
read -r -d '' SITECUSTOMIZE_BODY <<EOF || true
# AUTO-GENERATED by scripts/apply_lightrag_atomic_write_patch.sh (ISSUES #47).
# Do not edit by hand — re-run the script to regenerate.
import os
import sys

_REPO_ROOT = os.environ.get("OMNIGRAPH_REPO_ROOT", "${REPO_ROOT}")
if _REPO_ROOT and _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

try:
    from lib.lightrag_atomic_write_patch import apply as _apply_atomic_write

    _apply_atomic_write()
except Exception:  # noqa: BLE001 — fail-soft: never block interpreter startup
    pass
EOF

applied=0
for venv in "$REPO_ROOT/venv-aim1" "$REPO_ROOT/venv"; do
  # Resolve the site-packages dir for whichever python layout exists.
  for sp in "$venv"/lib/python*/site-packages "$venv"/Lib/site-packages; do
    if [[ -d "$sp" ]]; then
      printf '%s\n' "$SITECUSTOMIZE_BODY" > "$sp/sitecustomize.py"
      echo "  wrote $sp/sitecustomize.py"
      applied=$((applied + 1))
      break
    fi
  done
done

if [[ "$applied" -eq 0 ]]; then
  echo "WARNING: no venv site-packages found under $REPO_ROOT (venv-aim1 / venv)" >&2
  exit 1
fi
echo "ISSUES #47 atomic-write sitecustomize applied to $applied venv(s)."
